version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: gmmo-postgres-dev
    environment:
      POSTGRES_DB: gmmo_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: gmmo-pgadmin-dev
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"

  mssql:
    container_name: gmmo-mssql
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      ACCEPT_EULA: Y
      MSSQL_SA_PASSWORD: ${MSSQL_SA_PASSWORD}
    networks:
      servicebus-net:
        aliases:
          - mssql

  servicebus-emulator:
    container_name: gmmo-servicebus-emulator
    image: mcr.microsoft.com/azure-messaging/servicebus-emulator:latest
    pull_policy: always
    volumes:
      - ./servicebus-config:/ServiceBus_Emulator/ConfigFiles
    ports:
      - "5672:5672"
      - "5300:5300"
    environment:
      SQL_SERVER: mssql
      MSSQL_SA_PASSWORD: ${MSSQL_SA_PASSWORD}
      ACCEPT_EULA: Y
      SQL_WAIT_INTERVAL: ${SQL_WAIT_INTERVAL}
    depends_on:
      - mssql
    networks:
      servicebus-net:
        aliases:
          - sb-emulator

networks:
  servicebus-net:
    driver: bridge

volumes:
  postgres_data:
